### ISSUE TITLE
jmeter 4.0 ZooKeeper 连接异常

### ISSUE THREAD

**Issue by chutian52** [dubbo/jmeter-plugins-dubbo#10]
异常信息：
java.lang.IOException: Packet Len1213480860 out of range

Jmeter版本 4.0
Jmeter-plugins-dubbo： 1.3.3-with-dependencies

**Comment by ningyu1** [comment]
@chutian52 
jmeter版本4.0测试可用，参考下图：

![image](https://user-images.githubusercontent.com/3387548/40903133-f3947a5c-6808-11e8-8847-03354ac70eec.png)
![image](https://user-images.githubusercontent.com/3387548/40903184-226d32c4-6809-11e8-9e86-ecf3518770af.png)
![image](https://user-images.githubusercontent.com/3387548/40903188-25f0cf82-6809-11e8-9280-ce8485a6f6dd.png)
![image](https://user-images.githubusercontent.com/3387548/40903194-28f4ffaa-6809-11e8-90fa-1865fcd4e3bd.png)

**Comment by ningyu1** [comment]
@chutian52 你可以吧jmeter完整的错误日志发出来，一起讨论

**Comment by ningyu1** [comment]
@chutian52 我现在关闭这个issue，如果有问题你可以reopen这个issue
