### ISSUE TITLE
插件性能这么高？！

### ISSUE THREAD

**Issue by zheteng123** [dubbo/jmeter-plugins-dubbo#11]
这是用咱们插件测试的结果：
![image](https://user-images.githubusercontent.com/14845275/40914223-e9b94c26-6829-11e8-8e12-1ad255b29db7.png)
这是用我们自己的jar包方式测试的结果：
![image](https://user-images.githubusercontent.com/14845275/40914252-018c9da8-682a-11e8-82be-a83d49b5b2b4.png)

同样的接口及参数，差距这么大吗？？

还想请教下，直接调zk地址，还有调服务的dubbo地址，从性能上来讲有区别吗？

**Comment by ningyu1** [comment]
我先关闭这个issue，如果有问题你可以reopen
