### ISSUE TITLE
jmeter3.2/3.3版本命令行执行时不能生成jmeter.log

### ISSUE THREAD

**Issue by zheteng123** [dubbo/jmeter-plugins-dubbo#12]
纯净版的jmeter3.2/3.3，只在lib/ext下放了插件包jmeter-plugins-dubbo-1.3.3-jar-with-dependencies.jar，命令行执行./jmeter.sh -n -t test_next.jmx时，提示DubboShutdownHook WARN Unable to register Log4j shutdown hook because JVM is shutting down.
且jmeter.log为空，见下面截图:
![image](https://user-images.githubusercontent.com/14845275/40958104-a3ff427a-68ca-11e8-9f3d-c4adc5b206c8.png)

正常http协议应该生成jmeter.log日志文件，如下：
![image](https://user-images.githubusercontent.com/14845275/40958035-60f0dfb6-68ca-11e8-83bb-d22820909f25.png)

不知道是否有遇到同样问题的同学

**Comment by ningyu1** [comment]
我认为应该是jmeter环境的问题，我先关闭这个issue，如果有问题你可以reopen
