### ISSUE TITLE
jmeter4.0使用1.3.3版本请求成功但是响应数据中没有预期的值

### ISSUE THREAD

**Issue by shuhg1989** [dubbo/jmeter-plugins-dubbo#13]
使用jmeter4.0，插件使用1.3.3的版本，请求dubbo账户信息的接口，响应数据中没有相关的账户信息返回，请帮忙看看是什么原因
![image](https://user-images.githubusercontent.com/30462453/41076192-f93628ca-6a42-11e8-85ae-6cd5048270b8.png)

结果返回
![image](https://user-images.githubusercontent.com/30462453/41076208-0f9d9454-6a43-11e8-893d-5779859cbfd2.png)

**Comment by shuhg1989** [comment]
使用dubbo直连就可以了

**Comment by ningyu1** [comment]
@shuhg1989 检查zk中是否已经有service注册，以及检查注册的url与调用的url是否匹配，如果不匹配检查Consumer Settings设置，比如说是否有version、group之类
