### ISSUE TITLE
返回值中存在乱码

### ISSUE THREAD

**Issue by hostpost114** [dubbo/jmeter-plugins-dubbo#14]
返回值中存在乱码
   jmeter显示为：
             "commodityName":"?????"
       
   后台日志：
             "commodityName":"WMNS BLAZER LOW PRINT"

**Comment by ningyu1** [comment]
@hostpost114 参考FAQ解决中文乱码：https://github.com/dubbo/jmeter-plugins-dubbo/wiki/FAQ
