### ISSUE TITLE
rpc.filter.GenericFilter.invoke

### ISSUE THREAD

**Issue by hostpost114** [dubbo/jmeter-plugins-dubbo#15]
自定义类调用异常

![_15289726324669](https://user-images.githubusercontent.com/31546102/41407468-17013be6-7002-11e8-8baa-a0d70a926e83.png)

{"code":1,"detailMessage":"Failed to invoke remote method: $invoke, provider: dubbo://172.17.222.109:7001/com.wonhigh.udc.es.service.WechatQryService?application\u003dDubboSample\u0026async\u003dfalse\u0026cluster\u003dfailfast\u0026connections\u003d100\u0026dubbo\u003d1.3.2-SNAPSHOT-jar-with-dependencies\u0026generic\u003dtrue\u0026interface\u003dcom.wonhigh.udc.es.service.WechatQryService\u0026loadbalance\u003drandom\u0026pid\u003d11980\u0026register.ip\u003d172.17.232.32\u0026retries\u003d0\u0026side\u003dconsumer\u0026timeout\u003d10000\u0026timestamp\u003d1528970537174\u0026version\u003d1.0.0, cause: com.alibaba.dubbo.rpc.RpcException: com.wonhigh.udc.es.service.WechatQryService.qryWechats(java.lang.String, com.wonhigh.udc.es.dto.PageDto)\r\ncom.alibaba.dubbo.rpc.RpcException: com.wonhigh.udc.es.service.WechatQryService.qryWechats(java.lang.String, com.wonhigh.udc.es.dto.PageDto)\r\n\tat com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:107)\r\n\tat com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)\r\n\tat com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)\r\n\tat com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)\r\n\tat com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)\r\n\tat com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)\r\n\tat com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)\r\n\tat com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)\r\n\tat com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)\r\n\tat com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)\r\n\tat com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\nCaused by: java.lang.NoSuchMethodException: com.wonhigh.udc.es.service.WechatQryService.qryWechats(java.lang.String, com.wonhigh.udc.es.dto.PageDto)\r\n\tat java.lang.Class.getMethod(Class.java:1786)\r\n\tat com.alibaba.dubbo.common.utils.ReflectUtils.findMethodByMethodSignature(ReflectUtils.java:816)\r\n\tat com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:57)\r\n\t... 13 more\r\n","cause":{"localAddress":{},"remoteAddress":{},"detailMessage":"com.alibaba.dubbo.rpc.RpcException: com.wonhigh.udc.es.service.WechatQryService.qryWechats(java.lang.String, com.wonhigh.udc.es.dto.PageDto)\r\ncom.alibaba.dubbo.rpc.RpcException: com.wonhigh.udc.es.service.WechatQryService.qryWechats(java.lang.String, com.wonhigh.udc.es.dto.PageDto)\r\n\tat com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:107)\r\n\tat com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)\r\n\tat com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)\r\n\tat com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)\r\n\tat com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)\r\n\tat com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)\r\n\tat com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)\r\n\tat com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)\r\n\tat com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)\r\n\tat com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)\r\n\tat com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\nCaused by: java.lang.NoSuchMethodException: com.wonhigh.udc.es.service.WechatQryService.qryWechats(java.lang.String, com.wonhigh.udc.es.dto.PageDto)\r\n\tat java.lang.Class.getMethod(Class.java:1786)\r\n\tat com.alibaba.dubbo.common.utils.ReflectUtils.findMethodByMethodSignature(ReflectUtils.java:816)\r\n\tat com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:57)\r\n\t... 13 more\r\n","stackTrace":[{"declaringClass":"com.alibaba.dubbo.remoting.exchange.support.DefaultFuture","methodName":"returnFromResponse","fileName":"DefaultFuture.java","lineNumber":218},{"declaringClass":"com.alibaba.dubbo.remoting.exchange.support.DefaultFuture","methodName":"get","fileName":"DefaultFuture.java","lineNumber":137},{"declaringClass":"com.alibaba.dubbo.remoting.exchange.support.DefaultFuture","methodName":"get","fileName":"DefaultFuture.java","lineNumber":111},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker","methodName":"doInvoke","fileName":"DubboInvoker.java","lineNumber":95},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.AbstractInvoker","methodName":"invoke","fileName":"AbstractInvoker.java","lineNumber":142},{"declaringClass":"com.alibaba.dubbo.rpc.filter.GenericImplFilter","methodName":"invoke","fileName":"GenericImplFilter.java","lineNumber":172},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1","methodName":"invoke","fileName":"ProtocolFilterWrapper.java","lineNumber":68},{"declaringClass":"com.alibaba.dubbo.monitor.support.MonitorFilter","methodName":"invoke","fileName":"MonitorFilter.java","lineNumber":74},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1","methodName":"invoke","fileName":"ProtocolFilterWrapper.java","lineNumber":68},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter","methodName":"invoke","fileName":"FutureFilter.java","lineNumber":53},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1","methodName":"invoke","fileName":"ProtocolFilterWrapper.java","lineNumber":68},{"declaringClass":"com.alibaba.dubbo.rpc.filter.ConsumerContextFilter","methodName":"invoke","fileName":"ConsumerContextFilter.java","lineNumber":47},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1","methodName":"invoke","fileName":"ProtocolFilterWrapper.java","lineNumber":68},{"declaringClass":"com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper","methodName":"invoke","fileName":"ListenerInvokerWrapper.java","lineNumber":73},{"declaringClass":"com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler","methodName":"invoke","fileName":"InvokerInvocationHandler.java","lineNumber":51},{"declaringClass":"com.alibaba.dubbo.common.bytecode.proxy16","methodName":"$invoke","fileName":"proxy16.java","lineNumber":-1},{"declaringClass":"cn.tsoft.framework.testing.jmeter.plugin.dubbo.sample.DubboSample","methodName":"callDubbo","fileName":"DubboSample.java","lineNumber":463},{"declaringClass":"cn.tsoft.framework.testing.jmeter.plugin.dubbo.sample.DubboSample","methodName":"sample","fileName":"DubboSample.java","lineNumber":321},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"executeSamplePackage","fileName":"JMeterThread.java","lineNumber":490},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"processSampler","fileName":"JMeterThread.java","lineNumber":416},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"run","fileName":"JMeterThread.java","lineNumber":250},{"declaringClass":"java.lang.Thread","methodName":"run","fileName":null,"lineNumber":-1}],"suppressedExceptions":[]},"stackTrace":[{"declaringClass":"com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker","methodName":"doInvoke","fileName":"DubboInvoker.java","lineNumber":100},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.AbstractInvoker","methodName":"invoke","fileName":"AbstractInvoker.java","lineNumber":142},{"declaringClass":"com.alibaba.dubbo.rpc.filter.GenericImplFilter","methodName":"invoke","fileName":"GenericImplFilter.java","lineNumber":172},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1","methodName":"invoke","fileName":"ProtocolFilterWrapper.java","lineNumber":68},{"declaringClass":"com.alibaba.dubbo.monitor.support.MonitorFilter","methodName":"invoke","fileName":"MonitorFilter.java","lineNumber":74},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1","methodName":"invoke","fileName":"ProtocolFilterWrapper.java","lineNumber":68},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter","methodName":"invoke","fileName":"FutureFilter.java","lineNumber":53},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1","methodName":"invoke","fileName":"ProtocolFilterWrapper.java","lineNumber":68},{"declaringClass":"com.alibaba.dubbo.rpc.filter.ConsumerContextFilter","methodName":"invoke","fileName":"ConsumerContextFilter.java","lineNumber":47},{"declaringClass":"com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1","methodName":"invoke","fileName":"ProtocolFilterWrapper.java","lineNumber":68},{"declaringClass":"com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper","methodName":"invoke","fileName":"ListenerInvokerWrapper.java","lineNumber":73},{"declaringClass":"com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler","methodName":"invoke","fileName":"InvokerInvocationHandler.java","lineNumber":51},{"declaringClass":"com.alibaba.dubbo.common.bytecode.proxy16","methodName":"$invoke","fileName":"proxy16.java","lineNumber":-1},{"declaringClass":"cn.tsoft.framework.testing.jmeter.plugin.dubbo.sample.DubboSample","methodName":"callDubbo","fileName":"DubboSample.java","lineNumber":463},{"declaringClass":"cn.tsoft.framework.testing.jmeter.plugin.dubbo.sample.DubboSample","methodName":"sample","fileName":"DubboSample.java","lineNumber":321},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"executeSamplePackage","fileName":"JMeterThread.java","lineNumber":490},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"processSampler","fileName":"JMeterThread.java","lineNumber":416},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"run","fileName":"JMeterThread.java","lineNumber":250},{"declaringClass":"java.lang.Thread","methodName":"run","fileName":null,"lineNumber":-1}],"suppressedExceptions":[]}

**Comment by devotion987** [comment]
@hostpost114 为何关闭了？怎么解决的？我也遇到这个问题
