### ISSUE TITLE
group  设置错误

### ISSUE THREAD

**Issue by jinyingone** [dubbo/jmeter-plugins-dubbo#16]
group为：dubbo/TEST
这个样的group，会报参数异常
查看源码，group的配置应该放在
case Constants.REGISTRY_ZOOKEEPER:
			registry = new RegistryConfig();
			registry.setProtocol(Constants.REGISTRY_ZOOKEEPER);
			registry.setAddress(getAddress());
            **String group = getGroup();
            registry.setGroup(StringUtils.isBlank(group) ? null : group);**
            reference.setProtocol(getRpcProtocol().replaceAll("://", ""));
            reference.setRegistry(registry);
			break;

**Comment by ningyu1** [comment]
@jinyingone 这个问题我需要和dubbo commit讨论一下

**Comment by ningyu1** [comment]
@jinyingone 你们group为何要在register配置，插件中的group是service的分组属性，我看了一下register的group作用是更改zk里注册的root路径，所以我不太明白你们的用法？

**Comment by ningyu1** [comment]
@jinyingone 我觉得应该是混淆了两者的使用，我关闭这个问题

**Comment by jinyingone** [comment]
registry 设置了group之后,每个service就不用设置group了
这样就可以区分环境了

**Comment by ningyu1** [comment]
@jinyingone 区分环境应该使用分环境的注册中心服务，用这种方式似乎不太好，dubbo官方的文档中没有标记registry的group使用用途，因此不太建议这样使用

**Comment by jinyingone** [comment]
恩,这个能支持下吗,我记得之前官方文档是有这个选项的,最新的版本文档上没了,但实际还是可以用的
