### ISSUE TITLE
包装类型不能传null

### ISSUE THREAD

**Issue by FurionCS** [dubbo/jmeter-plugins-dubbo#18]
比如 Integer 传null 会出现格式转换异常

**Comment by ningyu1** [comment]
@FurionCS 空就可以了

**Comment by FurionCS** [comment]
错误异常
{
    "detailMessage":"For input string: \"\"",
    "stackTrace":
    [
        {
            "declaringClass":"java.lang.NumberFormatException",
            "methodName":"forInputString",
            "fileName":"NumberFormatException.java",
            "lineNumber":65
        },
          {
            "declaringClass":"java.lang.Long",
            "methodName":"parseLong",
            "fileName":"Long.java",
            "lineNumber":601
        },
        {
            "declaringClass":"java.lang.Long",
            "methodName":"valueOf",
            "fileName":"Long.java",
            "lineNumber":803
        },



![image](https://user-images.githubusercontent.com/16729832/41967702-c1257740-7a34-11e8-9815-4429dd9bb273.png)


谢谢你的回复！！

**Comment by ningyu1** [comment]
@FurionCS thanks. 
我昨天修复了一个版本[V1.3.5](https://github.com/dubbo/jmeter-plugins-dubbo/releases/tag/V1.3.5)

**Comment by FurionCS** [comment]
谢谢你的修复
