### ISSUE TITLE
请教一个泛型问题

### ISSUE THREAD

**Issue by zephyrzoom** [dubbo/jmeter-plugins-dubbo#19]
dubbo接口参数使用自定义泛型Generic<Object>这种，该插件是否支持？（Wiki中只列出了List和Map泛型）

**Comment by ningyu1** [comment]
@zephyrzoom 能不能举个例子详细说明一下你想要的参数泛型示例？

**Comment by zephyrzoom** [comment]
类似这样`Response<Message> someService(Request<Message> request)`
Response和Request是自定义的泛型

**Comment by ningyu1** [comment]
@zephyrzoom 支持的
paramType：your.package.Request<your.package.Message>
paramValue：Request<Message>这个对象序列化后的json字符串

**Comment by zephyrzoom** [comment]
@ningyu1 谢谢

**Comment by ningyu1** [comment]
@zephyrzoom 支持的，使用方法我在[FAQ](https://github.com/dubbo/jmeter-plugins-dubbo/wiki/FAQ)的复杂参数传递示例中

**Comment by ningyu1** [comment]
问题已经解决，关闭这个issue

**Comment by SeaYang** [comment]
@ningyu1 ，参数类型为：io.githun.ningyu.RequestVo<MyClassVo>，泛型<MyClassVo>在RequestVo.items属性上，并且RequestVo还有别的属性，这个时候怎么填写paramType和paramValue呢？多谢！

**Comment by SeaYang** [comment]
@ningyu1 因为当RequestVo还有别的属性的时候，试了多次都是失败的，provider不能正确将参数转换为实体类

**Comment by ningyu1** [comment]
> @ningyu1 ，参数类型为：io.githun.ningyu.RequestVo，泛型在RequestVo.items属性上，并且RequestVo还有别的属性，这个时候怎么填写paramType和paramValue呢？多谢！

{"属性1":"属性值" , "items": {"class": "io.githun.ningyu.MyClassVo","items对象的属性1": "属性值"}}

**Comment by SeaYang** [comment]
@ningyu1 多谢！
