### ISSUE TITLE
"Not found exported service: com.xxx.AccountService, may be version or group mismatch!"报错

### ISSUE THREAD

**Issue by wanweipk** [dubbo/jmeter-plugins-dubbo#23]
请求：
![image](https://user-images.githubusercontent.com/17780764/43526077-f105e898-95d5-11e8-9232-dc0c41506632.png)
返回结果：
"Not found exported service: com.XXX.AccountService, may be version or group mismatch!"

插件版本1.3.6

服务接口都有的
![image](https://user-images.githubusercontent.com/17780764/43526286-6955ad06-95d6-11e8-8fa5-6964b17a26be.png)

**Comment by wanweipk** [comment]
接口没有version和group

**Comment by ningyu1** [comment]
@wanweipk 错误很明显可能version或者group设置错误没有找到接口服务，`telnet`使用`ls`只能看到接口、方法名称，想要看到version和group信息请使用`ls -l `查看：

![image](https://user-images.githubusercontent.com/3387548/43558220-ebd17dc8-963a-11e8-8b59-e803bf9f3d66.png)

**Comment by wanweipk** [comment]
![image](https://user-images.githubusercontent.com/17780764/43558293-5050a71a-963b-11e8-9424-4c8092967a58.png)确实没看到

**Comment by ningyu1** [comment]
@wanweipk `generic=false` 你们禁用了泛化调用，插件是使用泛化方式进行调用的

**Comment by wanweipk** [comment]
了解，谢啦啊

**Comment by wanweipk** [comment]
这个还不是这个这个问题，这个标识说明当前不是泛化调用。方便加一下wx 15606811369吗

**Comment by ningyu1** [comment]
@wanweipk 你这个provider接口中的`generic`属性是如何加进去的？我能了解一下你们服务端使用的dubbo版本吗？  wx: ningyu8794

**Comment by ningyu1** [comment]
@wanweipk 问题解决了吗？如果解决了可以关闭这个issue

**Comment by ningyu1** [comment]
我先关闭这个问题，有问题可以reopen
