### ISSUE TITLE
使用自定义javabean做参数，javabean要放在哪里？

### ISSUE THREAD

**Issue by HelloXiaoHe** [dubbo/jmeter-plugins-dubbo#24]
如题

**Comment by ningyu1** [comment]
@HelloXiaoHe 如果使用的是1.3.x的版本不需要添加api中需要的javabean的jar包。
如果使用的是1.2.x的版本需要将api中需要的javabean的jar包放入到${JMETER_HOME}\lib\ext

参考：
https://github.com/dubbo/jmeter-plugins-dubbo/wiki/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97
wiki中的《接口包依赖添加方式》部分

**Comment by HelloXiaoHe** [comment]
这个不用匹配数据类型吗？相当于发送json？

**Comment by ningyu1** [comment]
@HelloXiaoHe  对的，请求时参数格式都是json，返回的数据也会序列化成json格式返回到jmeter的查看结果树中

**Comment by mengxun900123** [comment]
java范型的接口入参怎么匹配数据类型呢？比如这接口：findDisChannelItemByChannelCodeAndVid(OprRequest<DisChannelVirtualIn> paramOprRequest);我应该写那个bean呢

**Comment by HelloXiaoHe** [comment]
写你这个类OprRequest 的包名和文件名，com.xxx.xx.OprRequest

**Comment by ningyu1** [comment]
@mengxun900123 
参考:https://github.com/dubbo/jmeter-plugins-dubbo/wiki/FAQ#%E5%A4%8D%E6%9D%82%E5%8F%82%E6%95%B0%E4%BD%BF%E7%94%A8%E6%A1%88%E4%BE%8B

你上面的异常可能是泛型的类型`<DisChannelVirtualIn>`并不在`OprRequest`.param属性上

**Comment by fan0412** [comment]
@mengxun900123  你的问题解决了吗？我也遇到类似的问题

**Comment by ningyu1** [comment]
@fan0412 参考wiki中FAQ中的参数示例
