### ISSUE TITLE
目前版本支不支持dubbo直连模式

### ISSUE THREAD

**Issue by jxgxldl** [dubbo/jmeter-plugins-dubbo#27]
想绕过注册中心，问下目前版本支不支持dubbo直连模式跑dubbo接口？

**Comment by ningyu1** [comment]
@jxgxldl 有直连方式，wiki中有说明

1. Protocol=none为直连方式
2. Protocol=zookeeper使用zk注册中心
3. Protocol=multicast为广播方式
4. Protocol=redis使用redis注册中心
5. Protocol=simple使用simple注册中心
