### ISSUE TITLE
返回结果是：Failed to invoke remote method: $invoke, provider: dubbo://10.104.6.9:20881/com.fpx.workflow.service

### ISSUE THREAD

**Issue by zlbkkk** [dubbo/jmeter-plugins-dubbo#30]
![1](https://user-images.githubusercontent.com/33144389/48175468-26ec3e80-e347-11e8-85a7-17d2e7e77978.png)
这个大概是什么原因呢

**Comment by ningyu1** [comment]
https://ningyu1.github.io/site/about/index.html 里面有微信
