### ISSUE TITLE
使用该插件，报错“"Not found exported service: xxx.MockService, may be version or group mismatch!"

### ISSUE THREAD

**Issue by zhuofengxichen** [dubbo/jmeter-plugins-dubbo#33]

**Comment by ningyu1** [comment]
这个就是检查一下接口的版本号（version）和分组（group）的对应关系，有可能你的接口的版本和分组跟插件中填写的不一样，修改成一样即可，如果没有就清空输入框不用填写

**Comment by zhuofengxichen** [comment]
配置的是一样的，本地代码通过泛化可以调用，但是使用插件不行

**Comment by ningyu1** [comment]
使用什么方式调用？zk还是直连？服务端接口暴漏的url是什么？可以提供出来吗

**Comment by zhuofengxichen** [comment]
1、使用zk方式调用
2、看了下源码，发现是字段定义不太一样，把你ui里的group当成了zk的group，改了下源码，ok了。

**Comment by ningyu1** [comment]
@zhuofengxichen 
插件的group使用的是service的group属性，不是registry的group，不过下个版本可以把registry的group配置项放开到ui上设置

**Comment by fyxgit** [comment]
目前有个应用场景，dubbo sample之后的请求，上下文变量获取到。流程如下：

1. 调用http请求，登陆某个接口，根据返回值通过正则提取登陆的：token

2. 调用dubbo sample这个插件执行其他接口调用。

3. 获取步骤一的${token}，进行接口调用。  ====> 问题在于：由于步骤2的dubbo sample没有中断，导致${token}变量没有获取到。

**Comment by ningyu1** [comment]
[V1.3.8](https://github.com/dubbo/jmeter-plugins-dubbo/releases/tag/V1.3.8)
