### ISSUE TITLE
请教如果传参是ENUM类型如何处理

### ISSUE THREAD

**Issue by ribrib1234** [dubbo/jmeter-plugins-dubbo#34]
测试过程中使用到的枚举类代码如下：
public enum SubscribeChannelType {

	WE_CHAT(2), MOBILE_APP(5);

	private int code;

	SubscribeChannelType(int code) {
		this.code = code;
	}

	public int getCode() {
		return code;
	}

	public void setValue(int code) {
		this.code = code;
	}

	public static SubscribeChannelType convert(int value) {
		SubscribeChannelType result = null;
		for (SubscribeChannelType item : SubscribeChannelType.values()) {
			if (item.getCode() == value) {
				result = item;
				break;
			}
		}
		return result;
	}

}

**Comment by zhuofengxichen** [comment]
你这边能用起来吗

**Comment by ribrib1234** [comment]
我这边枚举类型用不起来，正常的简单类型、复杂类型可以

**Comment by ningyu1** [comment]
感谢你们的提问，我会针对枚举类型看一下的，我会把处理结果发出来

**Comment by ribrib1234** [comment]
好的，谢谢处理

**Comment by ningyu1** [comment]
@ribrib1234 @zhuofengxichen 
目前测试下来有两种方式可以解决：
1. 不升级插件版本的情况下，将接口的api jar包加入jmeter classpath下可以正常的使用枚举参数
ps. 枚举参数的传递方式例如：paramType：com.xxx.SubscribeChannelType，paramValue：WE_CHAT
ps. api jar包加入jmeter classpath下有两种方式，第一种将jar包放入JMETER_HOME/ext/lib目录下，第二种在jmeter ui上添加入下图所示
![image](https://user-images.githubusercontent.com/3387548/48688116-b1625700-ebff-11e8-9307-e4f415ca2dc8.png)

2. 新版本的插件推崇的就是不使用api jar的方式即可调用接口，想要不使用api jar包来支持自定义枚举参数的需要等待下一个版本的插件升级，后面我会升级一个小版本[bugfix]来特殊处理一下枚举参数

**Comment by ningyu1** [comment]
@ribrib1234 就这几天刚好和其他几个问题一起修改后发布

**Comment by ningyu1** [comment]
[V1.3.8](https://github.com/dubbo/jmeter-plugins-dubbo/releases/tag/V1.3.8)

**Comment by mawenlong3** [comment]
> 引入JAR的方式可以解决目前的需求，期待下次的版本更新

请问一下 这个问题怎么解决的，我也同样引入了jar包，但是枚举类型的数据在json里面怎么写都不能用

**Comment by ningyu1** [comment]
@mawenlong3 枚举就当做字符串传递就可以了
