### ISSUE TITLE
出现日志依赖冲突

### ISSUE THREAD

**Issue by zhuofengxichen** [dubbo/jmeter-plugins-dubbo#35]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/xxx/Documents/performance/apache-jmeter-3.0/lib/ext/ApacheJMeter_core.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/xxx/Documents/performance/apache-jmeter-3.0/lib/ext/jmeter-plugins-dubbo-1.3.7-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]

**Comment by ningyu1** [comment]
@zhuofengxichen 这个是warn级别的？，应该不影响使用

**Comment by ningyu1** [comment]
issue我先关闭了，如果有新的问题随时reopen
