### ISSUE TITLE
一个线程组不支持多个不同service的dubbo sampler, 配置多个时，只有一个sampler能调用成功

### ISSUE THREAD

**Issue by zhuofengxichen** [dubbo/jmeter-plugins-dubbo#39]

**Comment by ningyu1** [comment]
@zhuofengxichen 一个线程组下多个dubbo sample没有问题，你具体是什么问题？发个截图看看

**Comment by zhuofengxichen** [comment]
不同的接口单独跑都没有问题；但是配置多个不同的service是有问题的，其中一个运行正常，另一个service的报错看截图，
![image](https://user-images.githubusercontent.com/4944976/48897101-29d94a00-ee84-11e8-8486-96993228b628.png)
代码里定位的问题是，genericService为null，所以报了这个错误

**Comment by ningyu1** [comment]
我测试下来没有问题
![image](https://user-images.githubusercontent.com/3387548/48909830-3de37280-eea9-11e8-9e59-bffd5f209dd7.png)
![image](https://user-images.githubusercontent.com/3387548/48909860-5489c980-eea9-11e8-8aeb-95357ac4f1fe.png)
![image](https://user-images.githubusercontent.com/3387548/48909879-623f4f00-eea9-11e8-8db2-3676d6a33ce0.png)
![image](https://user-images.githubusercontent.com/3387548/48909890-76834c00-eea9-11e8-8b9c-c308310a0356.png)

**Comment by ningyu1** [comment]
@zhuofengxichen 检查一下你的request中的信息是不是某个属性没有对应上

**Comment by ningyu1** [comment]
issue我先关闭，如果有问题随时reopen
