### ISSUE TITLE
dubbo sample之后的请求无法获取到参数化变量

### ISSUE THREAD

**Issue by fyxgit** [dubbo/jmeter-plugins-dubbo#41]
目前有个应用场景，dubbo sample之后的请求，提取的上下文变量没有获取到。流程如下：

1. 调用http请求，登陆某个接口，根据返回值通过正则提取登陆的：token

2. 调用dubbo sample这个插件执行其他接口调用。

3. 获取步骤一的${token}，进行接口调用。但是没有获取到token的值。  

====> 问题在于：由于步骤2的dubbo sample没有中断，导致${token}变量没有获取。

**Comment by ningyu1** [comment]
@fyxgit 我的理解第一步结束就已经获取到token值并且放入变量中，跟第二步请求没有直接关系。
获取token返回值肯定是在第一步结束之后就执行从第一步返回值解析赋值token变量，你为什么要等第二步结束之后再获取呢？

**Comment by fyxgit** [comment]
是这样的，token确实是在第一步已经通过正则表达式匹配出来了。但是因为第二步需要去执行dubbo请求。token的变量引用是在第三步的http请求中！现在的情况是：假如我的第三步http请求中不去引用token是可以执行到的，一旦引用了token，则http请求没有执行到！

发自我的 iPhone

**Comment by ningyu1** [comment]
你的意思是三个请求，其中前后各一个http请求，中间是一个dubbo请求，你的变量是如何设置到jmeter中的？ 是通过beanshell还是说其他的？ 我试过的，vars.put("key","value")，在dubbo sample之后的其他各种sample都可以${key}引用到

**Comment by fyxgit** [comment]
1：变量token是根据第一个请求的返回值，正则匹配获取，第三个请求中通过: ${token}来引用。
2：目前我测试结果发现的规律是：windows系统下，通过gui和命令行（jmeter -n -t file.jmx）来运行是ok的。
3：**linux**系统下（mac系统）下通过gui运行也是ok的，_唯独在命令行_（jmeter -n -t file.jmx）运行失败，执行不到第三个请求。

**Comment by ningyu1** [comment]
感谢反馈，我测试一下这个具体场景有结果给你反馈

**Comment by fyxgit** [comment]
该问题的原因已找到，原因是：命令行下jemter的调试运行的时间设置为1秒，由于dubbo请求完成，关闭连接耗时较久，导致在1s的规定时间内，没有足够的时间执行到后面的请求。在这里要感谢作者的对于问题的及时反馈。
