### ISSUE TITLE
部分泛型无法正确转换

### ISSUE THREAD

**Issue by maomaofeitui** [dubbo/jmeter-plugins-dubbo#42]
如下形式的泛型参数通过插件请求
public class Request  《T  extends  Serializable 》 implements Serializable {
    private String requestSystem;
    private String operator;
    private T params;
}
参数如下：
{"operator":"2313131313131","params":{"class": "RefundReqDTO","id":"1231313"},"requestSystem":"23131313131","traceLogId":"23131231313"}；

服务端会解析成Request(requestSystem=23131313131, operator=2313131313131, traceLogId=23131231313, params={class=RefundReqDTO, id=1231313})服务端无法正常识别params
正常通过dubbo自带的telnet会解析成
Request(requestSystem=2312313, operator=123, traceLogId=sdasadada, params=RefundReqDTO(id=123131313))

**Comment by ningyu1** [comment]
@maomaofeitui 
"params":{"class": "RefundReqDTO","id":"1231313" 
这个RefundReqDTO要写类的完全类名类似于：com.xxx.RefundReqDTO

**Comment by maomaofeitui** [comment]
> @maomaofeitui
> "params":{"class": "RefundReqDTO","id":"1231313"
> 这个RefundReqDTO要写类的完全类名类似于：com.xxx.RefundReqDTO

这个只是举个例子，类名我填写的是全路径的，我把下面这个地方的直接把入参用fastjson转成JSONObject的就好了。
					Class<?> clazz = Class.forName(className);
						paramterTypeList.add(arg.getParamType());
						parameterValuesList.add(isBlank(arg.getParamValue()) ? null : JsonUtils.formJson(arg.getParamValue(), clazz));

**Comment by ningyu1** [comment]
@maomaofeitui 
我测试了一下没有问题，泛型不会丢失，如下图：

测试参数类：
```
public class Request<T extends Serializable> implements Serializable {
    private static final long serialVersionUID = -5409636923593800173L;
    private String requestSystem;
    private String operator;
    private T params;
}
public class TestVo implements Serializable {
    private static final long serialVersionUID = 669046662643377966L;
    private PType type;
    private String name;
}
```

测试provider接口：
```
public interface ITest {
    void sayHello(Request<TestVo> param);
}
```

jmeter中请求参数类型：
```
com.jiuyescm.account.vo.Request
```

jmeter中请求参数json数据：
```
{"operator":"2313131313131","params":{"class": "com.xxx.vo.TestVo","name":"1231313"},"requestSystem":"23131313131","traceLogId":"23131231313"}
```

provider端断点查看参数对象：

![image](https://user-images.githubusercontent.com/3387548/50152780-93237000-02ff-11e9-8244-0223a60848a1.png)

**Comment by ningyu1** [comment]
你是不是在jmeter的classpath下添加了api的jar包？插件使用泛化调用不需要依赖api jar包

**Comment by maomaofeitui** [comment]
> 你是不是在jmeter的classpath下添加了api的jar包？插件使用泛化调用不需要依赖api jar包

嗯，原来的有一套基于spring的dubbo插件，但是处理不了泛型，就加了这个插件做补充。

**Comment by ningyu1** [comment]
@maomaofeitui 所有的当map处理后当遇到参数类型为枚举的话就会出现问题

**Comment by maomaofeitui** [comment]
> @maomaofeitui 所有的当map处理后当遇到参数类型为枚举的话就会出现问题

学到了。
