### ISSUE TITLE
java.lang.NoClassDefFoundError添加参数后就报错，无法保存，保存时也报错。求助

### ISSUE THREAD

**Issue by mileslian** [dubbo/jmeter-plugins-dubbo#46]
使用
dubbo-2.5.3.jar
javassist-3.15.0-GA.jar
zookeeper-3.4.6.jar
zkclient-0.1.jar
jline-0.9.94.jar
netty-3.7.0-Final.jar
slf4j-api-1.7.5.jar
log4j-over-slf4j-1.7.5.jar
及jmeter-plugins-dubbo-1.3.2-SNAPSHOT.jar版本以上
报错内容Uncaught Exception java.lang.NoClassDefFoundError: org/springframework/util/StringUtils. See log file for details.
<img width="757" alt="error" src="https://user-images.githubusercontent.com/20573589/50204798-fd402180-03a0-11e9-8261-4ba2bb936d4c.png">
![error1](https://user-images.githubusercontent.com/20573589/50204861-295ba280-03a1-11e9-863a-030b2b008503.png)

使用jmeter-plugins-dubbo-${version}-jar-with-dependencies.jar的不会。

**Comment by ningyu1** [comment]
这个类org.springframework.util.StringUtils所在的jar包没有放入JAVA_HOME/lib/ext下
使用jmeter-plugins-dubbo-${version}-jar-with-dependencies.jar这个包是因为这个已经将所有的依赖打入到插件里所以不会出现class not found。
使用jmeter-plugins-dubbo-1.3.2-SNAPSHOT.jar这个包只包含插件的东西，第三方依赖的jar包需要人工放入JAVA_HOME/lib/ext下，建议使用jmeter-plugins-dubbo-${version}-jar-with-dependencies.jar。
具体可以参考[用户指南](https://github.com/dubbo/jmeter-plugins-dubbo/wiki/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97)中的说明。
![image](https://user-images.githubusercontent.com/3387548/50216912-1ad1b300-03c2-11e9-89dc-be7369bd8169.png)
第三方依赖包不局限于图片中的这些包，需要结合自己场景使用的具体第三方包

**Comment by mileslian** [comment]
太感谢了，已解决。
