### ISSUE TITLE
请问一下在自定义的对象中有一个参数是Enum的该怎么填写啊

### ISSUE THREAD

**Issue by gosuTopData1** [dubbo/jmeter-plugins-dubbo#51]
这时候Args里面的paramType是自定义对象xxx.yyy.zzz.AAA，paramValue是一个json，有a，b，c三个参数，其中c是aaa.bbb.ccc.MMM的枚举类，这时候json中c这个key的value应该怎么填写啊？

**Comment by ningyu1** [comment]
@gosuTopData1 
paramType -> xxx.yyy.zzz.AAA
paramValue -> {"a":"v1","b":"v2","c":"枚举值字符串"}

**Comment by gosuTopData1** [comment]
> @gosuTopData1
> 就当做字符串传入
> paramType -> xxx.yyy.zzz.AAA
> paramValue -> {"a":"v1","b":"v2","c":"枚举值字符串"}

我是这么传的结果在dubbo sample的结果树中有"c":"aaa.bbb.ccc.MMM.valueA"的值，但是服务收到请求中的没有c的值，jmeter中也没有报错
这是为什么？

**Comment by gosuTopData1** [comment]
哦，搞定了，不需要传aaa.bbb.ccc.MMM.valueA，只要传valueA就可以了......
