### ISSUE TITLE
参数支持读CSV文件？

### ISSUE THREAD

**Issue by xiehong0114** [dubbo/jmeter-plugins-dubbo#59]
压测场景，接口入参数据量很大支持类似HTTP请求那样，从csv文件读取变量值？或者这种压测场景变量的参数该如何传？

**Comment by ningyu1** [comment]
支持，查看在V1.1.0就支持具体可以查看：https://github.com/dubbo/jmeter-plugins-dubbo/releases/tag/V1.1.0

**Comment by xiehong0114** [comment]
OK,完美解决~
