### ISSUE TITLE
使用1.3版本，无法反序列化java.util.Currency

### ISSUE THREAD

**Issue by ganjx** [dubbo/jmeter-plugins-dubbo#6]
使用1.3版本，无法反序列化java.util.Currency，请问如何处理呢
JDK版本：1.6

**Comment by ningyu1** [comment]
@ganjx 能不能把具体异常发出来

**Comment by ganjx** [comment]
java.lang.RuntimeException: Illegal constructor: java.util.Currency

**Comment by ningyu1** [comment]
@ganjx 你是把它（java.util.Currency）当做接口参数？还是接口返回值？

**Comment by ganjx** [comment]
请求参数。

**Comment by ganjx** [comment]
我们是有个Meony字段，然后Currency是Money中的一个属性。
private BigDecimal               amount;
    private Currency                 currency;

**Comment by ningyu1** [comment]
@ganjx json反序列化必须要有无参的构造器

**Comment by ganjx** [comment]
java.util.Currency  这是jdk自带的。。。
