### ISSUE TITLE
使用1.3.6版本，直连提供者经常出现报错

### ISSUE THREAD

**Issue by lzp492456131** [dubbo/jmeter-plugins-dubbo#62]
![image](https://user-images.githubusercontent.com/13482351/55269296-9057f400-52cc-11e9-85b0-1ac2209c4c65.png)
![image](https://user-images.githubusercontent.com/13482351/55269586-3bb67800-52d0-11e9-85cd-8f6add3b9732.png)

![image](https://user-images.githubusercontent.com/13482351/55238730-30cbfb00-5270-11e9-85e7-41badeba38f6.png)

**Comment by ningyu1** [comment]
@lzp492456131 超时太多调整timeout参数

**Comment by lzp492456131** [comment]
好的感谢
