### ISSUE TITLE
dubbo支持版本能否升级到2.7.x

### ISSUE THREAD

**Issue by ghostells** [dubbo/jmeter-plugins-dubbo#63]
我们目前项目服务端的dubbo版本升级到了2.7.2，插件目前最高只支持到2.6.x，目前使用最新的插件调用失败。感谢~

**Comment by ningyu1** [comment]
Dubbo 2.7.x应该是向下兼容的，具体的错误可以发出来看一下吗？
Dubbo 2.7.x兼容方案：http://dubbo.apache.org/zh-cn/blog/dubbo-compatible.html

**Comment by ningyu1** [comment]
@ghostells 
[Dubbo Jmeter Plugin 2.7.1](https://github.com/dubbo/jmeter-plugins-dubbo/releases/tag/2.7.1)

**Comment by ghostells** [comment]
非常感谢，我先试试
