### ISSUE TITLE
调用只有一个string参数的接口返回null

### ISSUE THREAD

**Issue by zheteng123** [dubbo/jmeter-plugins-dubbo#9]
参见这个问题中后面的参数截图
https://github.com/dubbo/jmeter-plugins-dubbo/issues/8#event-1658049047

**Comment by ningyu1** [comment]
@zheteng123 

你描述的这个问题是因为，你的服务端暴漏接口的时候没有选择version，但是jmeter 插件在访问的时候version默认填写的是1.0.0，因此报错其实你可以去看服务端的日志有详细的错误信息，删掉version的输入信息即可，例如下图:

![image](https://user-images.githubusercontent.com/3387548/40902679-65c6b88a-6807-11e8-8f7d-17b9019f00a3.png)

在查看结果树中可以看到信息如下：

![image](https://user-images.githubusercontent.com/3387548/40902742-a721cc3e-6807-11e8-89e9-99ddc3c5b224.png)
![image](https://user-images.githubusercontent.com/3387548/40902734-a0b00884-6807-11e8-8630-c7d901185ee3.png)
![image](https://user-images.githubusercontent.com/3387548/40902711-8b80ea3c-6807-11e8-9dba-9e37cda463ad.png)
